
#Azure DevOps smart contract auto deploy

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: DeployBlockchain
  steps:
    - script: |
        echo Beginning Agent preparation:

        sudo apt install npm -y
        sudo npm install -g truffle

        echo "Truffle is installed"

        npm i "@openzeppelin/contracts"
        npm i "@openzeppelin/contracts-upgradeable"

        echo "OpenZeppelin libraries are installed"

        echo "Beginning Truffle initiation. Folder contents:"
        ls -l

        echo "Moving to new contract folders: "

        mkdir truffle_environment
        cd truffle_environment

        echo "Truffle_Environment folder contents before init: "

        ls -l

        sudo truffle init

        echo "Truffle_Environment folder contents after init: "

        ls -l

        echo "Copying repository files to the directory: "

    - task: DownloadSecureFile@1
      name: TruffleConfig 
      inputs:
        secureFile: 'truffle-config.js'

    - script: |
        sudo cp $(TruffleConfig.secureFilePath) . 
        cat truffle-config.js

        echo "Beginning Compiling:"
        sudo truffle compile

- job: PublishArtifacts
  steps:
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: './build'
      ArtifactName: 'deploy_logs'
      publishLocation: 'Container'

  displayName: 'Agent Preparation'