
#Azure DevOps smart contract auto deploy

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: DeployBlockchain
  steps:
    - script: |
        echo Beginning Agent preparation:

        sudo apt install npm -y
        sudo npm install -g truffle dotenv @truffle/hdwallet-provider -y

        echo "Truffle is installed"

        npm i "@openzeppelin/contracts"
        npm i "@openzeppelin/contracts-upgradeable"

        echo "OpenZeppelin libraries are installed"

        echo "Beginning Truffle initiation. Folder contents:"
        ls -l

        echo "Moving to new contract folders: "

        mkdir truffle_environment
        cd truffle_environment

        echo "Truffle_Environment folder contents before init: "

        ls -l

        sudo truffle init

        echo "Truffle_Environment folder contents after init: "

        ls -l

    - task: DownloadSecureFile@1
      name: truffleconfig
      inputs:
        secureFile: 'truffle-config.js'
    - task: DownloadSecureFile@1
      name: env
      inputs:
        secureFile: '.env'

    - script: |
        echo "Copying repository files to the directory: "
        
        sudo cp $(truffleconfig.secureFilePath) . 
        sudo cp $(env.secureFilePath) . 

        sudo wget -P "./contracts" https://raw.githubusercontent.com/crypto-infinity/inft-db/main/contracts/standardNFT_DB.sol
        sudo wget -P "./contracts" https://raw.githubusercontent.com/crypto-infinity/inft-db/main/contracts/INFT_DB.sol
        sudo wget -P "./contracts" https://raw.githubusercontent.com/crypto-infinity/inft-db/main/contracts/royaltiesNFT_DB.sol
        sudo wget -P "./contracts" https://raw.githubusercontent.com/crypto-infinity/inft-db/main/contracts/dynamicNFT_DBService.sol

        echo "Contents of truffle_environment after DownloadGithub Task "

        ls -l

        echo "Contents of truffle_environment/contracts after DownloadGithub Task "
        ls -l ./contracts

    - task: DownloadGitHubRelease@0
      inputs:
        connection: 'crypto-infinity'
        userRepository: 'crypto-infinity/inft-db'
        defaultVersionType: 'specificTag'
        version: '119737075'
        itemPattern: '**/*.yaml'
        downloadPath: '.'

    - script: |
        echo "Beginning Compiling:"

        sudo truffle compile    

- job: PublishArtifacts
  dependsOn: DeployBlockchain
  steps:
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: './build'
      ArtifactName: 'deploy_logs'
      publishLocation: 'Container'