# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo Beginning Agent preparation
    sudo apt update
    sudo apt upgrade -y
    sudo apt install npm -y
    sudo npm install -g truffle

  displayName: 'Beginning agent preparation.'
